# Generated by Django 4.2.30 on 2026-06-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('running', 'Running on deck'), ('diving', 'Diving in restricted zone'), ('attire', 'Improper attire'), ('object', 'Prohibited object'), ('wristband', 'Missing wristband')], max_length=50)),
                ('confidence', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('screenshot_path', models.CharField(blank=True, max_length=500)),
                ('camera_id', models.CharField(default='CAM-01', max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
